config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
   get 'books/about' => 'books#about'
	# delete,create,newはdeviseが作成してくれる
  devise_for :users
  resources :users, only:[:index, :edit, :show, :update] do
    get :search, on: :collection
  end

  resources :books, only:[:new, :destroy, :index, :edit, :show, :create, :update] do
    resource :favorites, only:[:create, :destroy]
  	resource :post_comments, only: [:create,:show,:destroy] do
    post :confirm, action: :confirm_new, on: :new
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	attachment :image
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments,dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end

	 validates :title, presence: true
	 validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :books, dependent: :destroy
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
	attachment :profile_image

	validates :name, presence: true
	validates :introduction,    length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# before_actionはすべてのコントローラのアクションが実行する際に最初に行われる
	# デバイスのコントローラー用
	before_action :configure_permitted_parameters, if: :devise_controller?
    # authenticate_user！でログイン認証されてない場合home画面へリダイレクトとする
	before_action :authenticate_user!,except: [:top, :about]
	# カレントユーザーだけしかedit,update,destroyアクションは使えない。
	before_action :ensure_correct_user, {only: [:edit, :update]}

	# ログイン後にマイページに飛ぶ
	def after_sign_in_path_for(resource)
   		user_url(resource)
 	end
	# 名前ログインのために必要な記述
	protected
	# ログイン時のパラメーターを設定する
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
	# データ更新時のパラメーターを設定する
	def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


# ※カレントユーザー以外は直接リンクを入力しても編集ページにいけないようにする
def ensure_correct_user
  @book = Book.find(params[:id])
  # ※カレントユーザーIDがbook.user_idと同じでない場合はbooks_pathへ飛ばす !=はif notと同じ
  if current_user.id != @book.user_id
    flash[:notice] = "ページにアクセスする権限がありません"
    redirect_to(books_path)
  end
end

  # 検索用
    def search
      @new_book = Book.new
      @user_profile = current_user
      if params[:name].present?
        @search_books = Book.where(['title LIKE ?', "%#{params[:title]}%"])
      else
        @search_books = Book.none
      end
    end
  # 検索用ここまで

  def top
  end

  def about
  end
  # 画像の投稿を表示させる
  def new
    @new_book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path, notice:'You have updated book successfully.'
  end

  def create
    puts params[:title]
    @new_book = Book.new(book_params)
    @books = Book.all
    @user_profile = current_user
    # 今ログインしているユーザのIDをuser_idへ代入する。この項目を入力しないとviewへ送れない
    @new_book.user_id = current_user.id
    if @new_book.save
      redirect_to books_path(@new_book.id), notice:'You have updated book successfully.'
    else
      render :index
    end
  end

  def index
    @new_book = Book.new
    @books = Book.all
    @user_profile = current_user
      if params[:title].present?
        @search_books = Book.where(['title LIKE ?', "%#{params[:title]}%"])
      else
        @search_books = Book.none
      end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = Book.find(params[:id]).user
    @user_profile = current_user
    # コメントを表示する
    @comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_to book_path(book)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to book_path(book)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

    def destroy
        @book = Book.find(params[:book_id])
        @comment = PostComment.find_by(book_id: params[:book_id])
        @comment.destroy
        redirect_to book_post_comments_path(@book), notice: "コメント「#{@comment.comment}」を削除しました"
    end

	def show
        @new_book = Book.new
	    @book = Book.find(params[:book_id])
		@user_profile = current_user
	end

    def confirm_new
        @book = Book.find_by(params[:book_id])
	    @comment = PostComment.new(post_comment_params)
            # render用の記述
            @user_profile = current_user
            @new_book = Book.new
            @user = @book.user
        @comment.user_id = current_user.id
        @comment.book_id = @book.id
        render 'books/show' if @comment.invalid?
    end

    def create
        @user_profile = current_user
        #@user = Book.find(params[:id]).user
    	@book = Book.find_by(params[:book_id])
	    @comment = @book.post_comments.new(post_comment_params)
        @comment.user_id = current_user.id
    	if params[:back].present?
            @new_book = Book.new
            @user = @book.user
    		render 'books/show'
            # render。redirect_toを複数回使う時はreturunで
            return
    	end
    	if  @comment.save
    		redirect_to book_path(@book), notice: "コメント「#{@comment.comment}」を登録しました"
    	else
            @new_book = Book.new
            @user = @book.user
            render 'books/show'
    	end
    end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  # ※カレントユーザー以外は直接リンクを入力しても編集ページにいけないようにする
	def ensure_correct_user
	  @user = User.find(params[:id])
	  # ※カレントユーザーIDがbook.user_idと同じでない場合はbooks_pathへ飛ばす
	  @user_profire = current_user
	  if current_user.id != @user.id
	    redirect_to user_path(@user_profire)
	  end
	end

	# 検索用
	  def search
	  	@new_book = Book.new
	  	@user_profile = current_user
	  	@user_books = User.find(params[:id]).books
	    if params[:name].present?
	      @search_users = User.where(['name LIKE ?', "%#{params[:name]}%"])
	    else
	      @search_users = User.none
	    end
	  end
	# 検索用ここまで

	def new
		@user = User.new
	end

	def index
		@users = User.all
		@user_profile = current_user
		@new_book = Book.new
	end

	def show
	  @user = User.find(params[:id])
	  # Userテーブルからユーザデータを取り出してそれに紐づく内容をbooksとして表示する
	  @user_books = User.find(params[:id]).books
	  @new_book = Book.new
	  @user_profile = current_user
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		reset_session
  		redirect_to root_path, alert: "Signed out successfully."
	end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_side.html.erb
<body>
	<div class="container">

<!-- ここからエラーメッセージ -->
	<% if @new_book.errors.any? %>
	<div class="error-massage">
		  <h3><i class="fas fa-kiwi-bird"></i><%= @new_book.errors.count %>件のエラーがあります<i class="fas fa-kiwi-bird"></i></h3>
	    <% @new_book.errors.full_messages.each do |message| %>
		  <tr><li><%= message %></li></tr>
	    <% end %>
	</div>
    <% end %>
<!-- ここまでエラーメッセージ -->
  	<div class="row">
    <div class="col-xs-3">
	    <% if flash.now[:notice] %>
		　　<p><%= flash[:notice] %></p>
		<% end %>
<!-- ここからサイドバー -->
	<h2>プロフィール</h2>
		<%= attachment_image_tag @user_profile, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg",size:'100x100'%>
		<table class="table table-condensed">
			<tr>
				<th>名前</th>
				<td><%= @user_profile.name %></td>
			</tr>
			<tr>
				<th>自己紹介</th>
				<td><%= @user_profile.introduction %></td>
			</tr>
		</table>
		<p><%= link_to "",edit_user_path(@user_profile.id), class: "btn btn-funky-moon btn-fab glyphicon glyphicon-wrench" %></p>
	<%= form_for @new_book do |f| %>
		<h2>新規投稿</h2>
		 <div class="profile">
			<p><%= f.label :title %></p>
			<p><%= f.text_field :title, rows:'1' %></p>
			<p><%= f.label :body %></p>
			<p><%= f.text_area :body, rows:'3' %></p>

			<p><%= f.submit"create", class: "btn btn-funky-moon btn-fab fas fa-pastafarianism" %></p>
		</div>
	<% end %>
	</div>
</body>

app/views/books/about.html.erb
<body>
	<div class="container">
	<div class="row">
	<div class="top-message col-md-offset-3 col-md-6">
		<section>
			<h1>Welcome to
			<span class="glyphicon glyphicon-book"><strong>Bookers!</strong></span></h1>
			<p>In<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers,</strong></p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various books!</p>
		</section>

		<div class="button">
			<%= link_to"Log in",new_user_session_path, class:"btn btn-info btn-block" %>
			<%= link_to"Sign Up",new_user_registration_path, class:"btn btn-success btn-block" %>
		</div>
	</div>
	</div>
	</div>
</body>
</html>

app/views/books/edit.html.erb
<div class="container">
	<h1>eding book</h1>
	<%= form_for(@book) do |f| %>
	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :body %></p>
	<p><%= f.text_area :body %></p>
	<p><%= f.submit 'Update Book' %></p>
	<%= link_to'show',book_path(@book.id) %> /
	<%= link_to'Back',books_path,class:"fas fa-pastafarianism" %>
	<div class="past">
		<i class="fas fa-pastafarianism"></i>
	</div>
	<% end %>
</div>

app/views/books/index.html.erb
<%= render 'books/side'%>
	<div class="col-xs-9">
<h2>Books</h2>
<!-- 検索フォームここから -->
<p>検索</p>
<%= form_with method: :get, local: true do |f| %>
	<%= f.text_field :title %>
	<%= f.submit :search %>
<% end %>

<% @search_books.each do |f| %>
	<p>title</p>
	<p><%= f.title %></p>
 <% end %>

<!-- 検索フォームここまで -->
<table class="table table-hover">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Option</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<!-- books変数内から一つずつ取り出しbook変数へ -->
	<% @books.each do |book| %>
	<!-- bookとひもついているユーザーの画像データを表示させる -->
	<tbody>
		<tr>
			<td>
				<%= link_to user_path(book.user) do %>
					<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg",size:'40x40'%>
				<% end %>
			</td>
			<!-- タイトルにリンク付けする -->
			<td>
				<%= link_to(book_path(book.id)) do %>
					<%= book.title %>
				<% end %>
			</td>
			<!-- bodyを表示 -->
			<td><%= book.body %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<!-- book投稿一覧ここまで -->
</div>
</div>
</div>

app/views/books/show.html.erb
<!-- サイドバーを挿入 -->
<%= render 'books/side', books: @books %>
<div class="col-xs-9">
	<h2>Book detail</h2>
	<table class="table">
		<thead>
			<th>Title</th>
			<th>option</th>
			<th>comment</th>
			<th></th>
		</thead>
		<tbody>
<!-- bookとひもづくユーザーの画像データを表示させる。book.user -->
			<tr>
				<td><%= link_to user_path(@user) do %>

					<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
					<br>
					<%= @user.name %>
					<% end %></td>
<!-- bookとひもづくユーザーの画像データを表示ここまで -->

					<td><%= link_to book_path(@book) do %>
						<%= @book.title %><% end %></td>
					<td><%= @book.body %></td>
					<td><%= link_to book_post_comments_path(@book) do %>
						<%= @book.post_comments.count %>件のコメントがあります
						<% end %></td>


<!-- イイねボタンここから -->
<% if @book.favorited_by?(current_user) %>
<!-- favorited_by?自分が含まれている場合 -->
	<td>
		<%= link_to book_favorites_path(@book),method: :delete do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i><% end %>
		<%= @book.favorites.count %>いいね
	</td>
<!-- favorited_by?自分が含まれていない場合 -->
	<% else %>
	<td>
		<%= link_to book_favorites_path(@book),method: :post do %>
		<i class="fa fa-heart-o" aria-hidden="true"></i>
		<% end %>
		<%= @book.favorites.count %>いいね
	</td>
<% end %>
<!-- いいねボタンここまで -->




<!-- ログインしているユーザーの場合edit,destoryを表示させる -->
<% if @book.user == current_user %>
	<div class="edit_destroy">
		<td><%= link_to "Edit",edit_book_path(@book.id), class:"btn btn-success"%></td>
		<td><%= link_to "Destroy", book_path(@book.id),class:"btn btn-danger", method: :delete, data: {confirm: '削除しますか？'} %></td>
	</div>
<% end %>
<!-- ログインユーザーの表示ここまで -->


						</tr>
					</tbody>
				</table>
<!-- テーブルここまで -->


<div class="post">
<!-- ここからエラーメッセージ -->
	<% if @comment.errors.any? %>
		<div class="error-massage">
			<h3><i class="fas fa-kiwi-bird"></i> <%= @comment.errors.count %>件のエラーがあります <i class="fas fa-kiwi-bird fa-flip-horizontal"></i></h3>
			<% @comment.errors.full_messages.each do |message| %>
				<tr><li><%= message %></li></tr>
			<% end %>
		</div>
	<% end %>
<!-- ここまでエラーメッセージ -->





<!--　コメント投稿ここから -->
	<%= form_with model:[@book,@comment],url:confirm_new_book_post_comments_path(@book),local: true do |f| %>
		<p><%= f.text_area :comment, rows:'5',placeholder:"コメント"%></p>
		<p><%= f.submit'確認',class:"btn btn-info glyphicon glyphicon-share-alt" %></p>
	<% end %>
</div>
<!-- コメントここまで -->





			</div>
		</div>
	</div>
</body>
</html>

app/views/books/top.html.erb
<body>
	<div class="container">
	<section>
	<h1>Welcome to
		<span class="glyphicon glyphicon-book"></span>
		<strong>Bookers!</strong>
	</h1>
	</section>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!-- これはヘッダーに表示させるメニュー画面 -->
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
<!-- FontAwesomeアイコンを使用するための記述。スタイルシートの上に書くこと -->
    <script src="https://kit.fontawesome.com/2b9bb87bcc.js" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if flash.now[:notice] %>
    <p><% flash[:notice] %></p>
    <% end %>
</head>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
<!-- ユーザーがサインインしている場合 -->
      <% if user_signed_in? %>

<!-- ハンバーガーメニューを作る -->
          <ul class="navbar-right">
            <li>
              <%= link_to_unless_current " Home", user_path(current_user.id),class:"glyphicon glyphicon-home animated-hover"%>
            </li>
            <li>
              <%= link_to_unless_current " Users", users_path,class:"glyphicon glyphicon-user" %>
            </li>
            <li>
              <%= link_to_unless_current " Books", books_path,class:"glyphicon glyphicon-book" %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path,class:"glyphicon glyphicon-log-out",method: :delete,data: {confirm: "本当に削除しますか？"}%>
            </li>
            </ul>
          <!-- ユーザーがサインインしていない場合 -->
      <% else %>
          <ul class="navbar-right">
            <li>
              <%= link_to_unless_current " Home", root_path,class:"glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to_unless_current " about", books_about_path,class:"glyphicon glyphicon-link" %>
            </li>
            <li>
              <%= link_to_unless_current " sign up", new_user_registration_path,class:"glyphicon glyphicon-pencil" %>
            </li>
            <li>
              <%= link_to_unless_current " login", new_user_session_path,class:"glyphicon glyphicon-log-in" %>
            </li>
          </ul>
    <% end %>
  </div>
</header>

<%= yield %>

app/views/post_comments/confirm_new.html.erb
<body>
	<div class="container">
		<h2>登録内容の確認</h2>
		<%= form_with model:[@book,@comment],url:book_post_comments_path(@book),local: true do |f| %>
		<table class="table table-hover">
			<tbody>
				<tr>
					<%= f.hidden_field :comment %>
					<th><%= f.label :comment %></th>
					<td><%= @comment.comment %></td>
				</tr>
			</tbody>
		</table>
		<%= f.submit"戻る",name: 'back',class:'btn btn-secondary mr-3'%>
		<%= f.submit"登録",class:'btn btn-primary'%>
		<% end %>
	</div>
</body>
</html>

app/views/post_comments/show.html.erb
<%= render 'books/side'%>
	<div class="col-xs-9">
		<h2>comments</h2>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>投稿者名</th>
				<th>時間</th>
				<th>内容</th>
			</tr>
		</thead>
		<tbody>
			<% @book.post_comments.each do |comment| %>
			<tr>
				<td><%= comment.user.name %></td>
				<td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
				<td><%= comment.comment %></td>
				<td><%= link_to "削除",book_post_comments_path(comment.book.id,comment.id),method: :delete %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/edit.html.erb
<!-- ここからユーザ編集画面 -->
<div class="container">
    <% if @user.errors.any? %>
      <h4><%= @user.errors.count %> 件のエラーがあります｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡</h4>
      <% @user.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>
<section>
    <h2 class="form-header-title">User info</h2>
    <div class="form-body">
    <!-- ここにform_forを追加します -->
    <%= form_for(@user)do |f| %>
    <!-- 名前フォーム -->
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class:"user-edit-form",pracholder:"名前", maxlength:20 %></label>
        </div>

        <div class="form-group has-icon">
          <%= f.label :profile_image, "image" %>
          <!-- attachment_fieldにより画像選択用のボタンを表示させる -->
          <%= f.attachment_field :profile_image, placeholder:"プロフィール画像", id:"profile_icon" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class:"user-edit-form",pracholder:"自己紹介文" %>
        </div>

        <div class="action-group">
          <%= f.submit "Update User" %>
        </div>
    <% end %>
    </div>
</section>
</div>
  <!-- ここまでユーザー編集画面 -->

app/views/users/index.html.erb
<%= render 'books/side'%>
	<div class="col-xs-9">
<h2>Users</h2>

<!-- 検索フォームここから -->
<p>検索</p>
<%= form_with url: search_users_path, method: :get, local: true do |f| %>
	<%= f.text_field :name %>
	<%= f.submit :search %>
<% end %>

<!-- 検索フォームここまで -->


<table class="table table-hover">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<!-- 変数内から一つずつ取り出 -->
	<% @users.each do |user| %>
	<!-- とひもついているユーザーの画像データを表示させる -->
	<tbody>
		<tr>
			<td>
			<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg",size:'40x40'%>
			</td>
			<!-- タイトルにリンク付けする -->
			<td>
			<%= user.name %>
			</td>
			<!-- bodyを表示 -->
			<td><%= link_to'show',user_path(user.id) %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<!-- book投稿一覧ここまで -->
</div>
</div>
</div>

app/views/users/search.html.erb
<%= render 'books/side'%>
	<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-hover">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<% @search_users.each do |f| %>
		<tr>
			<td><%= attachment_image_tag f, :profile_image, :fill, 40, 40, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg",size:'40x40'%></td>
			<td><%= f.name %></td>
		</tr>
		 <% end %>
	</tbody>
</table>
</div>

app/views/users/show.html.erb
<%= render 'books/side', books: @books %>
      <div class="col-xs-9">
          <!-- book一覧（カレントユーザが投稿したもののみ表示） -->
          <h2>Books</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Option</th>
    </tr>
  </thead>
  <!-- user_booksにはユーザの投稿したbookが入っている -->
  <% @user_books.each do |book| %>
  <!-- bookとひもついているユーザーの画像データを表示させる -->
    <tbody>
      <tr>
          <td><%= link_to user_path(@user) do %>

                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
              <% end %></td>
        <!-- タイトルにリンク付けする -->
          <td><%= link_to book_path(book.id) do %>
                  <%= book.title %>
              <% end %></td>
          <!-- bodyを表示 -->
          <td><%= book.body %></td>
      </tr>
    </tbody>
  <% end %>
</table>
<!-- book一覧ここまで -->
      </div>
      </div>
      </div>
  </body>
</html>